<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php
            endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocartnewcolor"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>

                <div id="popup-modal">

                </div>

                <?= $block->getChildHtml('', true) ?>
                <h2>custom</h2>
            </div>


        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
<?php endif; ?>
<script type="text/javascript">
    require([
        "jquery",
        'mage/url',
        "Magento_Ui/js/modal/modal",
        'Magento_Customer/js/customer-data'
    ], function ($, urlBuilder, modal, customerData) {
       $('#product-addtocart-button').click(function () {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: "Advanced Checkout",
                buttons: [
                    {
                        text: $.mage.__('Proceed to checkout '),
                        click: function () {
                            window.location.href = '<?= $block->getUrl() . '/checkout' ?>';
                        }
                    },
                    {
                        text: $.mage.__('Clear'),
                        click: function () {
                            this.closeModal();
                            $.ajax({
                                url: urlBuilder.build('tigren/cart/clearcart'),
                                type: "POST",
                                showLoader: true,
                                success: function (response) {
                                    console.log(response);
                                    var sections = ['cart'];
                                    customerData.invalidate(sections);
                                    customerData.reload(sections, true);

                                },
                                error: function (error) {
                                    console.error(error);
                                }
                            })


                        }
                    }
                ]
            };
            var popupdata = $('<div />').append($('#popup-modal'));
            modal(options, popupdata);
            popupdata.modal('openModal');
        });
    });
</script>
